apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iex-trading
  description: Tanzu Banking Demo - IEX Trading
  tags:
    - spring
    - java
    - banking-demo
    - iex-trading
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=iex-trading'
spec:
  type: website
  owner: banking-demo-product-team
  system: banking-demo-system
  lifecycle: experimental