apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: quotes-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: quotes-service
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"
  source:
    git:
      url: https://github.com/MoSehsah/bank-demo.git
      ref:
        branch: main
    subPath: quotes-service
