#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.webServiceDeployName
  namespace: #@ data.values.namespaceToDeploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: web-ui-service
    #@ if data.values.hasTestsWebService:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"
  env:
    - name: WAVEFRONT_TOKEN
      value: #@ data.values.wavefrontToken
    - name: spring.cloud.config.uri
      value: 'http://config-server'
    - name: spring.cloud.config.fail-fast
      value: 'true'
    - name: spring.cloud.config.retry.max-interval
      value: "10000"
    - name: spring.cloud.config.retry.max-attempts
      value: "2000"
    - name: accountServiceName
      value: #@ data.values.accountServiceNameW
    - name: quoteServiceName
      value: #@ data.values.quoteServiceNameW
    - name: userServiceName
      value: #@ data.values.userServiceNameW
    - name: portfolioServiceName
      value: #@ data.values.portfolioServiceNameW
    - name: analyticsServiceName
      value: #@ data.values.analyticsServiceNameW
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchNameWebService
    subPath: web-ui
