#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.quoteServiceDeployName
  namespace: #@ data.values.namespaceToDeploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: quote-service
    #@ if data.values.hasTestsPortfolioService:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  params:
  - name: annotations
    value:
      #@ if data.values.autoScalingClass == "kpa":
      #@ if data.values.autoScalingMinScale:
      autoscaling.knative.dev/minScale: #@ data.values.autoScalingMinScale
      #@ end
      #@ if data.values.autoScalingMaxScale:
      autoscaling.knative.dev/maxScale: #@ data.values.autoScalingMaxScale
      #@ end
      #@ if data.values.autoScalingScaleDownDelay:
      autoscaling.knative.dev/scaleDownDelay: #@ data.values.autoScalingScaleDownDelay
      #@ end
      #@ end

      #@ if data.values.autoScalingClass == "hpa":
      autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
      autoscaling.knative.dev/metric: cpu
      #@ end
  build:
    env:
    - name: BP_JVM_VERSION
      #@ if data.values.javaVersion == 17:
      value: "17.*"
      #@ end
      #@ if data.values.javaVersion == 11:
      value: "11.*"
      #@ end
  env:
    - name: WAVEFRONT_TOKEN
      value: #@ data.values.wavefrontToken
    - name: spring.cloud.config.uri
      value: #@ "http://config-server."+data.values.namespaceToDeploy+".svc.cluster.local"
    - name: spring.cloud.config.fail-fast
      value: 'true'
    - name: spring.cloud.config.retry.max-interval
      value: "10000"
    - name: spring.cloud.config.retry.max-attempts
      value: "2000"
    #@ if data.values.eurekaState:
    - name: EUREKA_URL
      value: #@ data.values.eurekaURL
    #@ end

    #@ if data.values.enableRedisCachingQuoteService
    - name: spring.cache.type
      value: 'redis'
    - name: spring.redis.host
      value: 'redis-svc'
    - name: spring.redis.port
      value: 6379
    #@ end
    
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchNameQuoteService
    subPath: quote-service
