apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: banking-demo-quote-service
  description: Tanzu Banking Demo - Quote Service
  tags:
    - spring
    - java
    - banking-demo
    - quote-service
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=quote-service'
spec:
  type: service
  lifecycle: experimental
  owner: banking-demo-product-team
  system: banking-demo-system
  dependsOn:
    - component:dev/banking-demo-config-server
    - component:dev/banking-demo-discovery-server
    - component:dev/banking-demo-iex-trading
  providesApis:
    - quote-service