#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-deployment
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels:
      app: web-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: harbor.dorn.gorke.ml/banking-demo/web-ui:0.0.1-SNAPSHOT
        env:
        - name: spring.cloud.config.uri
          value: #@ "http://config-server."+ data.values.namespace + ".svc.cluster.local"
        - name: WAVEFRONT_TOKEN
          value: #@ data.values.wavefront.token
        - name: spring.cloud.config.fail-fast
          value: "true"
        - name: spring.cloud.config.retry.max-interval
          value: "10000"
        - name: spring.cloud.config.retry.max-attempts
          value: "2000"
        - name: EUREKA_URL
          value: #@ "http://discovery-server."+ data.values.namespace + ".svc.cluster.local/eureka"
        - name: DEP_NS
          value: #@ data.values.namespace
        - name: customFrontendVar
          value: #@ data.values.web_ui.customFrontendVar
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: #@ data.values.namespace
  labels:
    app: web-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-ui
  type: #@ data.values.service.type