apiVersion: v1
kind: Service
metadata:
  labels:
    app: wf-proxy
  name: wf-proxy
  namespace: dev
spec:
  ports:
    - name: "2878"
      port: 2878
      targetPort: 2878
  selector:
    app: wf-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wf-proxy
  name: wf-proxy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wf-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: wf-proxy
    spec:
      containers:
        - env:
            - name: JAVA_HEAP_USAGE
              value: 1650m
            - name: WAVEFRONT_TOKEN
              value: change-me
            - name: WAVEFRONT_URL
              value: https://vmware.wavefront.com/api
          image: wavefronthq/proxy:latest
          name: wf-proxy
          ports:
            - containerPort: 2878
          resources: {}
      restartPolicy: Always
