apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: Tanzu Banking Demo - user Service
  tags:
    - spring
    - java
    - banking-demo
    - user-service
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=user-service'
spec:
  type: service
  lifecycle: experimental
  owner: banking-demo-product-team
  system: banking-demo-system
  dependsOn:
    - component:dev/config-server
    - component:dev/discovery-server
  providesApis:
    - user-service