#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: discovery-server
  namespace: #@ data.values.namespaceToDeploy
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: discovery-server
    #@ if data.values.hasTestsWebService:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17.*"
  env:
    - name: WAVEFRONT_TOKEN
      value: #@ data.values.wavefrontToken
    - name: spring.cloud.config.uri
      value: #@ "http://config-server."+data.values.namespaceToDeploy+".svc.cluster.local"
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchNameDiscoveryServer
    subPath: discovery-server
