apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: banking-demo-discovery-server
  description: Tanzu Banking Demo - Spring Discovery Server
  tags:
    - spring
    - java
    - banking-demo
    - discovery-server
    - eureka
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=discovery-server'
spec:
  type: service
  owner: banking-demo-product-team
  system: banking-demo-system
  lifecycle: experimental
  dependsOn:
    - component:dev/banking-demo-config-server