info:
  component: Config Server
spring:
  application:
    name: configserver
  # profiles:
  #   active: native
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        # native:
        #   searchLocations: file:${user.dir}/../config-data
# If you want to point to the main git,
#  then comment out spring.profiles.active and spring.cloud.config.server.native
#  and uncomment spring.cloud.config.server.git
       git:
         uri: https://github.com/MoSehsah/bank-demo.git
         searchPaths: config-data
         default-label: main
         
management:
  context_path: /admin
server:
  port: 8888